version: "3.9"
services:
  processed_db:
    image: postgres:latest
    env_file:
      - src/db_processed/db_processed.env
    volumes:
      - ./src/db_processed/init-master.sh:/docker-entrypoint-initdb.d/init.sh
      - ./src/db_processed:/tmp/postgresql
    ports:
      - "5432:5432"
  processed_db_copy:
    image: postgres:latest
    volumes:
      - ./src/db_processed/init-slave.sh:/docker-entrypoint-initdb.d/init.sh
      - ./src/db_processed:/tmp/postgresql
    env_file:
      - src/db_processed/db_processed.env
    ports:
      - "5433:5432"
    links:
      - processed_db
  # parsed_sup:
  #   build: 
  #     context: ./src
  #     dockerfile: ./parsed_sup/Dockerfile
  #   depends_on:
  #     - crawler_queue
  #   ports:
  #     - "50051"
  # crawler_manager:
  #   build:
  #     context: ./src
  #     dockerfile: ./crawler_manager/Dockerfile
  #   depends_on:
  #     - crawler_queue
  # crawler:
  #   build: src/crawler
  #   restart: always
  #   scale: 10
  # crawler_queue:
  #   image: 'redis'
  #   ports:
  #     - "6379"
  # service:
  #   # restart: on-failure
  #   ports:
  #     - "3004:5000"
  #   build:
  #     context: ./src
  #     dockerfile: ./service/Dockerfile
  # service_cache:
  #   # restart: on-failure
  #   image: redis
  # gateway:
  #   build: src/gateway
  #   ports:
  #     - "3003:80"
