version: "3.9"
services:
  processed_db:
    image: postgres
    env_file:
      - src/db_processed/db_processed.env
    ports:
      - "5432"
  parsed_sup:
    build:
      context: ./src
      dockerfile: ./parsed_sup/Dockerfile
    ports:
      - "50051"
  crawler:
    build: src/crawler
  service:
    build:
      context: ./src
      dockerfile: ./service/Dockerfile
    scale: 2
  gateway:
    build: src/gateway
    ports:
      - "3003:80"
