version: "3.9"
services:
  processed_db:
    image: postgres
    env_file:
      - src/db_processed/db_processed.env
    ports:
      - "3000:5432"
  parsed_sup:
    build:
      context: ./src
      dockerfile: ./parsed_sup/Dockerfile
    ports:
      - "3001:50051"
  crawler:
    build: src/crawler