version: "3.9"
services:
  processed_db:
    image: postgres
    env_file:
      - src/db_processed/db_processed.env
    ports:
      - "5432"
  parsed_sup:
    build:
      context: ./src
      dockerfile: ./parsed_sup/Dockerfile
    depends_on:
      - crawler_queue
    ports:
      - "50051"
  crawler_manager:
    build:
      context: ./src
      dockerfile: ./crawler_manager/Dockerfile
    depends_on:
      - crawler_queue
  crawler:
    build: src/crawler
    # restart: on-failure
  crawler_queue:
    image: 'redis'
    ports:
      - "6379"
  service:
    # restart: on-failure
    ports:
      - "3004:5000"
    build:
      context: ./src
      dockerfile: ./service/Dockerfile
  service_cache:
    # restart: on-failure
    image: redis
  gateway:
    build: src/gateway
    ports:
      - "3003:80"
