# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import processed_sink_pb2 as processed__sink__pb2


class ProcessedSinkStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.submit = channel.unary_unary(
                '/ProcessedSink/submit',
                request_serializer=processed__sink__pb2.SubmitRequest.SerializeToString,
                response_deserializer=processed__sink__pb2.SubmitResponse.FromString,
                )


class ProcessedSinkServicer(object):
    """Missing associated documentation comment in .proto file."""

    def submit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProcessedSinkServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'submit': grpc.unary_unary_rpc_method_handler(
                    servicer.submit,
                    request_deserializer=processed__sink__pb2.SubmitRequest.FromString,
                    response_serializer=processed__sink__pb2.SubmitResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ProcessedSink', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProcessedSink(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def submit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ProcessedSink/submit',
            processed__sink__pb2.SubmitRequest.SerializeToString,
            processed__sink__pb2.SubmitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
