metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: false

# metricbeat.autodiscover:
#   providers:
#     - type: docker
#       hints.enabled: true

# metricbeat.autodiscover:
#   providers:
#     - type: docker
#       labels.dedot: true
#       templates:
#         - condition:
#             contains:
#               docker.container.name: elasticsearch # make sure that you use the correct name of the container
#           config:
#             - module: elasticsearch
#               metricsets: ["node", "node_stats"]
#               hosts: "elasticsearch:9200"

# metricbeat.modules:


# metricbeat.modules:
# - module: docker
#   metricsets:
#     - "container"
#     - "cpu"
#     - "diskio"
#     - "healthcheck"
#     - "info"
#     #- "image"
#     - "memory"
#     - "network"
#   hosts: ["unix:///var/run/docker.sock"]
#   period: 10s
#   enabled: true

processors:
   - add_docker_metadata:
      host: "unix:///var/run/docker.sock"
      match_source: true
      match_short_id: true

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  # username: '${ELASTICSEARCH_USERNAME:}'
  # password: '${ELASTICSEARCH_PASSWORD:}'

setup.kibana:
  host: "kibana:5601"


metricbeat.modules:
- module: postgresql
  metricsets:
    # Stats about every PostgreSQL database
    - database

    # Stats about the background writer process's activity
    - bgwriter

    # Stats about every PostgreSQL process
    - activity
  hosts: 
    - postgres://processed_db:5432?sslmode=disable 
    - postgres://processed_db_copy-1:5432?sslmode=disable 
    - postgres://processed_db_copy-2:5432?sslmode=disable 
  username: postgres
  password: admin