# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import crawler_manager_pb2 as crawler__manager__pb2


class CrawlerManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.register = channel.unary_unary(
                '/CrawlerManager/register',
                request_serializer=crawler__manager__pb2.RegisterRequest.SerializeToString,
                response_deserializer=crawler__manager__pb2.RegisterResponse.FromString,
                )
        self.pull = channel.unary_unary(
                '/CrawlerManager/pull',
                request_serializer=crawler__manager__pb2.PullRequest.SerializeToString,
                response_deserializer=crawler__manager__pb2.PullResponse.FromString,
                )


class CrawlerManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def pull(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CrawlerManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'register': grpc.unary_unary_rpc_method_handler(
                    servicer.register,
                    request_deserializer=crawler__manager__pb2.RegisterRequest.FromString,
                    response_serializer=crawler__manager__pb2.RegisterResponse.SerializeToString,
            ),
            'pull': grpc.unary_unary_rpc_method_handler(
                    servicer.pull,
                    request_deserializer=crawler__manager__pb2.PullRequest.FromString,
                    response_serializer=crawler__manager__pb2.PullResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CrawlerManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CrawlerManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CrawlerManager/register',
            crawler__manager__pb2.RegisterRequest.SerializeToString,
            crawler__manager__pb2.RegisterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def pull(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CrawlerManager/pull',
            crawler__manager__pb2.PullRequest.SerializeToString,
            crawler__manager__pb2.PullResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
