# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import crawler_pb2 as crawler__pb2


class CrawlerSupervisorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.submit = channel.unary_unary(
        '/CrawlerSupervisor/submit',
        request_serializer=crawler__pb2.SubmitRequest.SerializeToString,
        response_deserializer=crawler__pb2.SubmitResponse.FromString,
        )


class CrawlerSupervisorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def submit(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CrawlerSupervisorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'submit': grpc.unary_unary_rpc_method_handler(
          servicer.submit,
          request_deserializer=crawler__pb2.SubmitRequest.FromString,
          response_serializer=crawler__pb2.SubmitResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'CrawlerSupervisor', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
